version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: public_user
      POSTGRES_PASSWORD: publicN3xt!
      POSTGRES_DB: public_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: public_user
      MONGO_INITDB_ROOT_PASSWORD: publicN3xt!
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  order-service:
    build: ./spring-publicnext
    container_name: spring-publicnext
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongo
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/public_db
      SPRING_DATASOURCE_USERNAME: public_user
      SPRING_DATASOURCE_PASSWORD: publicN3xt!
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

  logging-service:
    build: ./spring-logging-service
    container_name: spring-logging-service
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://public_user:publicN3xt!@mongo:27017/public_db?authSource=admin

volumes:
  postgres_data:
  mongo_data:
